# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 728e785e3aa3bc47e189bed6cb29a61e62090b85ac12edae88836cc987ad9677e0fbec98442587969509cddcdd217a59f6fb44b217d1dcf677e853841e48671b

test:
  secret_key_base: 995e471b576dee877d0de3342c71bc140e0d1cc54e47ead223a2e48e4b93f5028592d6ff105d14d56c0bbda45d84ba0ed5b3973d8a7adb4ff10251b2894ec5b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
